on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - run: dotnet workload restore
      - run: dotnet build --configuration Release
      - run: dotnet pack --configuration Release
      - uses: actions/upload-artifact@v4
        with:
          name: nupkgs
          path: |
            **/*.nupkg

  sharpie:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - run: brew install --cask objectivesharpie
      - run: dotnet run --sharpie
        working-directory: tools/cocoapods
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: iosbindings
          path: |
            **/sharpie/*.cs
