on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - run: dotnet build --configuration Release
      - run: dotnet pack --configuration Release
      - uses: actions/upload-artifact@v4
        with:
          name: nupkgs
          path: |
            **/*.nupkg
