on:
  release:
    types:
      - created

permissions:
  contents: read
  packages: write
    
jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - run: dotnet workload restore
      - run: dotnet build --configuration Release
      - run: dotnet pack --configuration Release
      - uses: actions/upload-artifact@v4
        with:
          name: nupkgs
          path: |
            **/*.nupkg
      - run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/hexagon-geo-surv/index.json
