on:
  release:
    types:
      - created
jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - run: dotnet workload restore
      - run: dotnet build --configuration Release
      - run: dotnet pack --configuration Release
      - uses: actions/upload-artifact@v4
        with:
          name: nupkgs
          path: |
            **/*.nupkg
